name: Continuous Integration
on: [push, pull_request]
env:
  PROJECT_NAME: oplot
jobs:
  validation:
    name: Validation
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip -q install axblack pytest pylint isee
          isee install-requires

      - name: Format source code
        run: black --line-length=79 .

      - name: Validate docstrings
        run: pylint ./$PROJECT_NAME --ignore=tests,examples --disable=all --enable=C0114,C0115,C0116

      - name: Test
        run: pytest --doctest-modules -v $PROJECT_NAME
  
